title:             Seeking Coding
email:             koallamara@gmail.com
description:       새끼 프로그래머의 고군분투
author:            koallamara
baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "http://blackrockdigital.github.io"

# Social Profiles
github_username:   koallamara

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
baseurl:
